name: Engine Build Check

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-latest, Windows-latest]
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y g++-14 xorg-dev libgl1-mesa-dev
          echo "CC=gcc-14" >> $GITHUB_ENV
          echo "CXX=g++-14" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSTRICT_MODE=ON

      - name: Build Engine
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cmake --build build --config ${{ matrix.config }} -- /m
          else
            cmake --build build --config ${{ matrix.config }} -- -j$(nproc)
          fi
